version: "3.8"
services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
      - "4572:4572"
    environment:
      - SERVICES=s3
      - DEBUG=1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
