stages:
  start_localstack:
    cmd: docker-compose up -d
    deps:
      - docker-compose.yml

  aws:
    cmd:
      - aws --endpoint-url=http://localhost:4566 s3 mb s3://raw
      - aws --endpoint-url=http://localhost:4566 s3 mb s3://staging
      - aws --endpoint-url=http://localhost:4566 s3 mb s3://curated
    deps:
      - docker-compose.yml
    params:
      - params/aws.yaml:
          - bucket_name: raw
          - bucket_name: staging
          - bucket_name: curated
    always_changed: true

  unpack:
    cmd: python build/unpack_to_raw.py --input_dir data/raw --bucket_name raw --output_file_name combined_raw.csv
    deps:
      - build/unpack_to_raw.py
      - data/raw/train/
      - data/raw/test/
      - data/raw/dev/
    outs:
      - tmp/combined_raw.csv

  preprocess:
    cmd: python src/preprocess_to_staging.py --bucket_raw raw --bucket_staging staging --input_file combined_raw.csv --output_prefix preprocessed
    deps:
      - src/preprocess_to_staging.py
      - tmp/combined_raw.csv
    outs:
      - tmp/preprocessed_train.csv
      - tmp/preprocessed_dev.csv
      - tmp/preprocessed_test.csv

  process:
    cmd: python src/process_to_curated.py --bucket_staging staging --bucket_curated curated --input_file preprocessed_train.csv --output_file tokenized_train.csv
    deps:
      - src/process_to_curated.py
      - tmp/preprocessed_train.csv
    outs:
      - tmp/tokenized_train.csv
